using ShelfGuard.Domain.Entities;

namespace ShelfGuard.Domain.Interfaces;

/// <summary>
/// Promo signal for a catalog row (Slice 3). <c>State</c> is <c>"active"</c> (a promo discount
/// is running in at least one store right now) or <c>"upcoming"</c> (a promo starts within the
/// look-ahead window). Active wins over upcoming when a product has both across stores.
/// </summary>
public sealed record ItemPromoInfo(string State, DateTime? StartsAt, decimal? DiscountPercent);

/// <summary>
/// Slice 4c — the replenishment engine's recommendation for a catalog row, rolled up across the
/// tenant's stores. Each value is the <b>MAX</b> of the per-store figures (the highest single
/// number is the safe tenant-wide default to offer). Sourced entirely from the nightly worker
/// recompute (<c>product_buffer</c> + <c>product_adu</c>). A product is absent from the result
/// until the engine has written a <c>product_buffer</c> row for it in at least one store.
///
///   <c>SuggestedMinStock</c>    — reorder point: MAX(red + yellow) — top of the yellow zone
///   <c>SuggestedMaxStock</c>    — max on-hand target: MAX(total buffer) — top of the green zone
///   <c>SuggestedSafetyBuffer</c>— MAX(red zone) — the DDMRP safety stock
///   <c>AduEffective</c>         — MAX effective average daily usage (informational)
///   <c>CalculatedAt</c>         — most recent <c>product_buffer.CalculatedAt</c> across stores
/// </summary>
public sealed record ItemBufferSuggestion(
    decimal? SuggestedMinStock,
    decimal? SuggestedMaxStock,
    decimal? SuggestedSafetyBuffer,
    decimal? AduEffective,
    DateTime? CalculatedAt);

/// <summary>
/// Slice 5 — full promo detail for the single-product page banner. Same active/upcoming
/// resolution as <see cref="ItemPromoInfo"/> (one product, one store-scoped winner), plus the
/// real order-formula forecast: <c>OrderCoefficient</c> from an <b>applied</b>
/// <c>PromoCannibalization</c> row for this product's own winning discount (generated by
/// Application's CannibalizationService, manager-approved before it counts — never invented here).
/// Null when no cannibalization suggestion has been generated/applied for this promo yet; the
/// banner still shows the plain "order will increase automatically" message in that case.
/// </summary>
public sealed record ItemPromoDetail(
    string State, DateTime? StartsAt, decimal? DiscountPercent, decimal? OrderCoefficient);

public interface IItemRepository
{
    // B2: `uncategorized` — true → only items with no category; overrides categoryId. When
    // categoryId is set (and uncategorized is not true) the filter expands to that category's
    // whole subtree, not an exact match. Appended at the very end (still before ct) so no
    // pre-existing parameter's positional index shifts for existing callers/fakes.
    Task<List<Item>> GetAllAsync(
        Guid? categoryId,
        Guid? segmentId,
        string? managementType,
        bool? uncategorized = null,
        CancellationToken ct = default);

    // TASK-640: minPrice/maxPrice — additive range filter on Item.PriceRetail for the frontend
    // table filter UI. B2: uncategorized — see GetAllAsync above. Both appended at the very end
    // (still before ct) so no pre-existing parameter's positional index shifts for existing
    // callers/fakes (WriteOffServiceTests reads `ids` off a fixed positional index).
    Task<(List<Item> Items, int Total)> GetPagedAsync(
        Guid? categoryId,
        Guid? segmentId,
        string? managementType,
        string? search,
        IReadOnlyList<Guid>? ids,
        string? sortBy,
        bool? sortDescending,
        int page,
        int pageSize,
        decimal? minPrice = null,
        decimal? maxPrice = null,
        bool? uncategorized = null,
        CancellationToken ct = default);

    Task<Item?> GetByIdAsync(Guid id, CancellationToken ct = default);
    Task<Item?> GetByBarcodeAsync(string barcode, CancellationToken ct = default);
    Task<IReadOnlyList<Item>> GetByAnyBarcodeAsync(IReadOnlyList<string> barcodes, CancellationToken ct = default);

    /// <summary>
    /// Slice 3: promo state for the given catalog-page product ids, aggregated across every store
    /// of the tenant. Considers only <c>promo</c>-reason / campaign-linked discounts in
    /// <c>active</c> status. "upcoming" = starts in the future but within
    /// <paramref name="upcomingWithinDays"/>. Products with no promo are absent from the result.
    /// </summary>
    Task<IReadOnlyDictionary<Guid, ItemPromoInfo>> GetPromoStatesAsync(
        IReadOnlyList<Guid> productIds, int upcomingWithinDays, CancellationToken ct = default);

    /// <summary>
    /// Slice 4c: the nightly replenishment engine's suggested min/max/safety for the given
    /// catalog-page product ids, each rolled up as the MAX across the tenant's stores. Products
    /// with no <c>product_buffer</c> row yet are absent from the result. See
    /// <see cref="ItemBufferSuggestion"/>.
    /// </summary>
    Task<IReadOnlyDictionary<Guid, ItemBufferSuggestion>> GetBufferSuggestionsAsync(
        IReadOnlyList<Guid> productIds, CancellationToken ct = default);

    /// <summary>
    /// Slice 5: full promo detail for one product's own page — a dedicated one-shot query so the
    /// paged catalog list's <see cref="GetPromoStatesAsync"/> query shape is untouched. Null when
    /// the product has no active/near-future promo. See <see cref="ItemPromoDetail"/>.
    /// </summary>
    Task<ItemPromoDetail?> GetPromoDetailAsync(
        Guid productId, int upcomingWithinDays, CancellationToken ct = default);

    Task<List<ProductSupplierSetting>> GetSupplierSettingsAsync(Guid productId, CancellationToken ct = default);
    Task<bool> SupplierSettingExistsAsync(Guid productId, Guid supplierId, CancellationToken ct = default);

    Task AddAsync(Item product, CancellationToken ct = default);
    Task AddSupplierSettingAsync(ProductSupplierSetting setting, CancellationToken ct = default);
    void Update(Item product);
    Task SaveChangesAsync(CancellationToken ct = default);
}
