using ShelfGuard.Domain.Constants;

namespace ShelfGuard.Domain.Entities;

/// <summary>
/// B2B marketplace order placed by a client tenant with a supplier tenant
/// under an active <see cref="SupplierAgreement"/> (TASK-316).
/// OrderNumber is generated by the application layer (sequential per
/// supplier) and stored as plain text.
/// </summary>
public sealed class MarketplaceOrder
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public string OrderNumber { get; set; } = string.Empty;
    public Guid AgreementId { get; set; }
    public Guid SupplierTenantId { get; set; }
    public Guid ClientTenantId { get; set; }
    /// <summary>See <see cref="MarketplaceOrderStatus"/>.</summary>
    public string Status { get; set; } = MarketplaceOrderStatus.New;

    public string? Comment { get; set; }
    /// <summary>Filled when Status = cancelled.</summary>
    public string? CancelReason { get; set; }
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Client store the goods are headed to (TASK-586, ADR-033 Decision 2). Nullable at the DB —
    /// orders placed before this column existed have no possible backfill value. Required by
    /// application-layer validation for every order placed going forward (backend-developer).
    /// </summary>
    public Guid? DestinationStoreId { get; set; }

    /// <summary>
    /// Ukraine region code of the destination location, snapshotted at order creation (TASK-649).
    /// Deliberately a snapshot rather than a live join through <see cref="DestinationStoreId"/> —
    /// a location's <see cref="Location.RegionCode"/> may be corrected later, but delivery-time
    /// history must reflect where the goods actually went at the time (same rationale as ADR-033
    /// for receipts). Set by the order service; this migration only adds the column/property.
    /// Nullable — historical orders have no backfill value and are excluded from per-region stats.
    /// </summary>
    public string? DestinationRegionCode { get; set; }

    /// <summary>Set by the service layer when Status transitions to shipped.</summary>
    public DateTimeOffset? ShippedAt { get; set; }
    /// <summary>Supplier-entered delivery estimate (in days), captured at ship time.</summary>
    public int? EstimatedDeliveryDays { get; set; }
    /// <summary>
    /// Mutable supplier-set expected delivery date (supplier-portal expansion, plan D5). Distinct
    /// from <see cref="EstimatedDeliveryDays"/> (a one-time whole-day estimate captured at ship
    /// time): this is an absolute date the supplier can reschedule as many times as needed while
    /// the order is still shipped. Nullable — the column is landed here in Phase 1; the endpoint
    /// that sets/reschedules it and the "in transit" auto-order integration arrive in Phase 4.
    /// </summary>
    public DateOnly? ExpectedDeliveryDate { get; set; }
    /// <summary>Set by the service layer when Status transitions to delivered.</summary>
    public DateTimeOffset? DeliveredAt { get; set; }
    /// <summary>Supplier-entered explanation when delivery runs past the estimated window.</summary>
    public string? DelayReason { get; set; }

    /// <summary>Client-side user who placed the order.</summary>
    public Guid? CreatedByUserId { get; set; }
    /// <summary>
    /// Denormalized display name of the client user who placed the order (supplier-portal
    /// expansion, plan #4). Snapshotted at creation so a supplier session can show "who ordered"
    /// without a cross-tenant join into the client's <c>users</c> table (which its RLS forbids).
    /// Same pattern as <see cref="User.InvitedByName"/>. Nullable — pre-migration orders and
    /// seed data have no value.
    /// </summary>
    public string? CreatedByUserName { get; set; }
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;

    public SupplierAgreement? Agreement { get; init; }
    public ICollection<MarketplaceOrderItem> Items { get; init; } = new List<MarketplaceOrderItem>();
}
