"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Btn } from "@/components/ui/Btn";
import { API_BASE } from "@/lib/api";
import { useStoreContext } from "@/lib/useStoreContext";
import { useCancelPromotionCampaign, usePromotionCampaigns, usePublishPromotionCampaign } from "../hooks/usePromotionCampaigns";
import type { PromotionCampaignStatus } from "../types";
import { SectionTabs } from "./SectionTabs";
type Tab="running"|"past"|"draft";
const bucket=(status:PromotionCampaignStatus,endsAt:string|null):Tab=>status==="draft"?"draft":status==="published"&&(!endsAt||new Date(endsAt)>new Date())?"running":"past";
const assetUrl=(value:string|null)=>!value?undefined:/^https?:\/\//i.test(value)?value:`${API_BASE.replace(/\/$/,"")}/${value.replace(/^\//,"")}`;
export function PromoProductsSection(){
 const router=useRouter(), selectedStores=useStoreContext(s=>s.selectedStoreIds); const {data:all=[],isLoading,isError}=usePromotionCampaigns(); const publish=usePublishPromotionCampaign(), cancel=useCancelPromotionCampaign(); const [tab,setTab]=useState<Tab>("running");
 const campaigns=useMemo(()=>all.filter(x=>selectedStores.length===0||x.locationIds.some(id=>selectedStores.includes(id))).map(x=>({...x,imageUrl:assetUrl(x.imageUrl)??null})),[all,selectedStores]); const visible=campaigns.filter(x=>bucket(x.status,x.endsAt)===tab); const counts={running:campaigns.filter(x=>bucket(x.status,x.endsAt)==="running").length,past:campaigns.filter(x=>bucket(x.status,x.endsAt)==="past").length,draft:campaigns.filter(x=>bucket(x.status,x.endsAt)==="draft").length};
 async function doPublish(id:string){try{await publish.mutateAsync(id);toast.success("Акцію опубліковано")}catch(e){toast.error(e instanceof Error?e.message:"Не вдалося опублікувати")}}
 async function doCancel(id:string){if(!window.confirm("Зняти акцію з публікації та скасувати її знижки?"))return;try{await cancel.mutateAsync(id);toast.success("Акцію скасовано")}catch(e){toast.error(e instanceof Error?e.message:"Не вдалося скасувати")}}
 return <div style={{background:"#0D1117",border:"1px solid #1F2937",borderRadius:12,padding:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:18}}><div><h2 style={{color:"#E8EDF5",fontSize:15,margin:0}}>Акційні кампанії</h2><p style={{color:"#6B7280",fontSize:12,margin:"4px 0 0"}}>Банер новини, аудиторія та всі товари зі знижками в одному налаштуванні</p></div><Btn icon={<span aria-hidden="true">＋</span>} onClick={()=>router.push("/consumer-app/promotions/new")}>Створити акцію</Btn></div><SectionTabs items={(["running","past","draft"] as Tab[]).map(key=>({key,label:key==="running"?"Активні":key==="past"?"Минулі":"Чернетки",count:counts[key]}))} activeKey={tab} onChange={setTab} ariaLabel="Статус акції" />{isLoading&&<p style={{color:"#6B7280"}}>Завантаження…</p>}{isError&&<p style={{color:"#F87171"}}>Не вдалося завантажити акції</p>}{!isLoading&&visible.length===0&&<p style={{color:"#6B7280",fontSize:13}}>У цьому розділі акцій поки немає.</p>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,420px),1fr))",gap:12}}>{visible.map(x=><article key={x.id} style={{border:"1px solid #202938",borderRadius:10,padding:14,background:"#10151D",display:"flex",flexDirection:"column",gap:10}}><div style={{height:120,borderRadius:8,backgroundColor:x.backgroundColor,backgroundImage:x.imageUrl?`url(${x.imageUrl})`:undefined,backgroundSize:"cover",backgroundPosition:"center",display:"flex",alignItems:"end",padding:12,boxSizing:"border-box"}}><div><small style={{color:x.accentColor}}>{x.eyebrow}</small><div style={{color:"white",fontWeight:700}}>{x.title}</div></div></div><p style={{color:"#9CA3AF",fontSize:12,margin:0}}>{x.description}</p><div style={{display:"flex",gap:12,flexWrap:"wrap",color:"#6B7280",fontSize:11}}><span>{x.locationIds.length} магазинів</span><span>{x.products.length} товарів</span><span>{new Date(x.startsAt).toLocaleDateString()} — {x.endsAt?new Date(x.endsAt).toLocaleDateString():"безстроково"}</span></div><div style={{display:"flex",gap:8,marginTop:"auto"}}>{x.status==="draft"&&<Btn size="sm" variant="success" onClick={()=>doPublish(x.id)}>Опублікувати</Btn>}{x.status==="draft"&&<Btn size="sm" variant="ghost" onClick={()=>router.push(`/consumer-app/promotions/${x.id}/edit`)}>Редагувати</Btn>}{x.status!=="cancelled"&&<Btn size="sm" variant="danger" onClick={()=>doCancel(x.id)}>Скасувати</Btn>}</div></article>)}</div></div>
}
